apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  POSTGRES_DB: {{ .Values.db.name | b64enc }}
  POSTGRES_USER: {{ .Values.db.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc }}
  POSTGRES_URL: {{ .Values.db.url | b64enc }}
